DIR_LAB               = lab
NAME                  = course-spring-ai-intro
IMAGE_SOURCE          = https://github.com/spring-academy/course-maisey-spring-ai-intro
CONTAINER_REGISTRY    = 
CONTAINER_REPOSITORY  = course-maisey
version               = latest

env                   = local